"""empty message

Revision ID: 77275ecc5050
Revises: 67c130ca1ef3
Create Date: 2020-09-07 22:56:30.792986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77275ecc5050'
down_revision = '67c130ca1ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
